name: nginx-proxy

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d       # overrides content of /etc/conf.d/ inside the container
      - certs:/etc/nginx/certs:ro
    networks:
      - proxy-network
    restart: unless-stopped
    container_name: nginx

  dockergen:
    image: nginxproxy/docker-gen  
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - nginx
    networks:
      - proxy-network
    depends_on:
      - nginx
    restart: unless-stopped
    container_name: docker-gen

  acme-companion:
    image: nginxproxy/acme-companion
    environment:
      - NGINX_PROXY_CONTAINER=nginx
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen
    volumes:
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx
    restart: unless-stopped
    container_name: acme-companion


volumes:
  acme:
  certs:


networks:
  proxy-network:
    name: proxy-network
    driver: bridge
