version: '3.4'


services:
  actual_server:
    image: docker.io/actualbudget/actual-server:24.11.0
    ports:
      - "5006:5006"
    volumes:
      - actual-data:/data
    restart: unless-stopped
    container_name: actual_server


volumes:
  actual-data:
