version: "3.4"


services:
  webtop:
    image: lscr.io/linuxserver/code-server:latest
    env_file:
      - .env
    networks:
      - proxy
    volumes:
      - ./settings.json:/config/data/User/settings.json
    restart: unless-stopped
    container_name: code-server


networks:
  proxy:
    external: true
    name: proxy-network
