services:
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    env_file:
      - ./config/.env.librechat
      - ./config/.env.librechat.ovr
      - ./config/.env.meilisearch
      - ./config/.env.rag_api
    environment:
      - VIRTUAL_HOST=${DOMAIN_NAME}
      - LETSENCRYPT_HOST=${DOMAIN_NAME}
      - VIRTUAL_PORT=3080
    volumes:
      - ./config/librechat.yaml:/app/librechat.yaml:ro
      - images:/app/client/public/images
    networks:
      - proxy
      - backend
    depends_on:
      - mongodb
      - rag_api
    user: "${UID}:${GID}"
    restart: unless-stopped
    container_name: librechat

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb:/data/db
    networks:
      - backend
    user: "${UID}:${GID}"
    restart: unless-stopped
    container_name: lc-mongodb
    command: mongod --noauth

  meilisearch:
    image: getmeili/meilisearch:v1.7.3
    env_file:
      - ./config/.env.meilisearch
    volumes:
      - meili_data:/meili_data
    networks:
      - backend
    user: "${UID}:${GID}"
    container_name: lc-meilisearch
    restart: unless-stopped

  vectordb:
    image: pgvector/pgvector:latest
    environment:
      POSTGRES_DB: file_embeddings_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
        - pgdata2:/var/lib/postgresql/data
    networks:
      - backend
    container_name: vectordb
    restart: unless-stopped

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    env_file:
      - ./config/.env.rag_api
    environment:
      DB_HOST: vectordb
      POSTGRES_DB: file_embeddings_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    depends_on:
      - vectordb
    networks:
      - backend
    container_name: rag_api
    restart: unless-stopped


volumes:
  images:
  mongodb:
  meili_data:
  pgdata2:


networks:
  proxy:
    external: true
    name: proxy-network
  backend:
    external: false
    name: librechat-backend
