version: "3.4"


services:
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_API_URL=http://rag_api:8000
      - VIRTUAL_HOST=${DOMAIN_NAME}
      - LETSENCRYPT_HOST=${DOMAIN_NAME}
      - VIRTUAL_PORT=3080
    volumes:
      - ./librechat.yaml:/app/librechat.yaml:ro
      - images:/app/client/public/images
    networks:
      - proxy
      - backend
    depends_on:
      - mongodb
      - rag_api
    user: "${UID}:${GID}"
    restart: unless-stopped
    container_name: libre_chat

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb:/data/db
    networks:
      - backend
    user: "${UID}:${GID}"
    restart: unless-stopped
    container_name: chat-mongodb
    command: mongod --noauth

  meilisearch:
    image: getmeili/meilisearch:v1.7.3
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - meili_data:/meili_data
    networks:
      - backend
    user: "${UID}:${GID}"
    container_name: chat-meilisearch
    restart: unless-stopped

  vectordb:
    image: pgvector/pgvector:latest
    environment:
      POSTGRES_DB: file_embeddings_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
        - pgdata2:/var/lib/postgresql/data
    networks:
      - backend
    container_name: vectordb
    restart: unless-stopped

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    env_file:
      - .env
    environment:
      DB_HOST: vectordb
      POSTGRES_DB: file_embeddings_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      COLLECTION_NAME: libre-collection

    networks:
      - backend
    depends_on:
      - vectordb
    container_name: rag_api
    restart: unless-stopped


volumes:
  images:
  mongodb:
  meili_data:
  pgdata2:


networks:
  proxy:
    external: true
    name: proxy-network
  backend:
    external: false
    name: librechat-backend
