version: '3.9'


services:
  wireguard:
    build: .
    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
    networks:
      custom_net:
        ipv4_address: 172.30.1.2
    restart: unless-stopped
    container_name: wireguard

  nginx:
    image: nginx
    networks:
      custom_net:
        ipv4_address: 172.30.1.3
    container_name: nginx
    restart: unless-stopped


networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/24
